# Generated by Django 4.2.10 on 2024-02-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservices', '0002_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
