# Generated by Django 4.2.10 on 2024-02-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservices', '0003_delete_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
